# define parameters for calibration and identification process
# robot: staubli TX40
---
calibration:
  calib_level:
  non_geom:
  base_frame:
  tool_frame:
  markers:
    - ref_joint:
      measure: []
  free_flyer:
  nb_sample:
identification:
  robot_params:
    - q_lim_def: 1.57
      fv : [8.05, 5.53, 1.97, 1.11, 1.86, 0.65]
      fs : [7.14, 8.26, 6.34, 2.48, 3.03, 0.282]
      Ia : [0.362, 0.362, 0.0988, 0.0313, 0.0468, 0.0105]
      offset : [0.392, 1.37, 0.326, -0.102, -0.0288, 0.127]
      Iam6 : 0.00964
      fvm6 : 0.616
      fsm6 : 1.95
      reduction_ratio : [32.0, 32.0, 45.0, -48.0, 45.0, 32.0]
      ratio_essential : 30.0
      dq_lim_def : [0.05009095, 0.05009095, 0.07504916, 0.0715585,  0.05585054, 0.12217305]
      ddq_lim_def : 20.0
      tau_lim_def : 4.0
  problem_params:
    - is_external_wrench : False
      is_joint_torques : True
      force_torque : None
      external_wrench_offsets : False
      has_friction : True
      has_joint_offset : True
      has_actuator_inertia : True
      is_static_regressor : True
      is_inertia_regressor : True
      has_coupled_wrist: True
      embedded_forces : False
  processing_params:
    - cut_off_frequency_butterworth: 100.0
      ts : 0.0002
  tls_params:
    - mass_load : 0.0
      which_body_loaded : 0.0
      sync_joint_motion : False
...
