"""Noise floor of the TALOS table-contact held-out residual.

The synthetic touches are generated by the *true* model (true joint
placements, table poses and contact offset), then the recorded joint angles
get encoder noise. Evaluating the true model on the held-out touches
therefore leaves only what noise and IK tolerance put there: no calibration
can do better on average. Held-out checks compare the calibrated model with
this floor instead of with the uncalibrated model, whose error depends on
how large the randomly injected errors happen to be.
"""

from __future__ import annotations

import copy
import tempfile
from pathlib import Path

import numpy as np

from examples.talos_table_contact.utils.talos_table_tools import (
    TalosTableContactCalibration,
)

# Global seed for the identifiability probe inside initialize(), which draws
# random configurations from NumPy's global generator.
IDENTIFIABILITY_SEED = 1234

# Allowed held-out excess over the noise floor. Observed with the fixtures'
# 120 training touches per session: 0.76-1.07x (single chain) and
# 0.95-1.19x (two chains) on macOS; 1.5 leaves room for platform-level
# differences in IK and solver results (#48).
HELD_OUT_FLOOR_MARGIN = 1.5
KEYS = ("z_rmse_mm", "roll_rmse_deg", "pitch_rmse_deg")


def true_model_floor(robot, chain_truth, config_path, df_val) -> dict:
    """Gap metrics of the true model on ``df_val`` (see module docstring).

    ``chain_truth`` holds ``true_model``, ``true_table_pose`` and
    ``true_contact_offset`` for the chain that generated ``df_val``.
    """
    true_robot = copy.copy(robot)
    true_robot.model = chain_truth["true_model"]
    true_robot.data = chain_truth["true_model"].createData()

    path = Path(tempfile.mkdtemp(prefix="talos_floor_")) / "validation.csv"
    df_val.to_csv(path, index=False)
    calib = TalosTableContactCalibration(true_robot, str(config_path))
    calib.calib_config["data_file"] = str(path)
    calib._data_path = str(path)
    calib.set_nominal_table_poses(chain_truth["true_table_pose"])
    calib.set_nominal_contact_offset(chain_truth["true_contact_offset"])
    np.random.seed(IDENTIFIABILITY_SEED)
    calib.initialize()
    return calib.gap_metrics(np.zeros(len(calib.calib_config["param_name"])))
