#!/usr/bin/env python3

# Copyright [2021-2026] Thanh Nguyen
# Copyright [2022-2023] [CNRS, Toward SAS]

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Run the TALOS table-contact calibration end-to-end and report verification
+ validation metrics.

    python run_calibration.py                 # use the committed demo data
    python run_calibration.py --regenerate     # resynthesize fresh data
    python run_calibration.py --noise-deg 0.1  # noisier synthetic encoders

There is no real hardware data bundled with this example -- see README.md
for why (the physical rig lives in a separate ROS/HPP/Stack-of-Tasks repo,
not FIGAROH) -- so this script always runs against synthetic data with a
known ground truth, generated by generate_synthetic_data.py. That is what
makes "verify and validate" meaningful here: the injected ground truth is
known, so this script can report exactly how well the calibration
recovers it, not just that it "ran".
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

from generate_synthetic_data import (
    NOMINAL_CONTACT_OFFSET,
    NOMINAL_TABLE_POSE,
    build_dataset,
)
from utils.talos_table_tools import TalosTableContactCalibration

from figaroh.calibration.calibration_tools import cartesian_to_SE3
from figaroh.tools.geometric_calibration_export import export_geometric_calibration_yaml
from figaroh.tools.run_archive import archive_run, compute_run_dir

HERE = Path(__file__).parent
CONFIG_PATH = HERE / "config" / "talos_table_left_config.yaml"
DATA_DIR = HERE / "data"


def _load_split(calib: TalosTableContactCalibration, df: pd.DataFrame) -> None:
    """Point an already-initialized calibration at a different dataset,
    reusing its existing base-parameter basis (a held-out split)."""
    N = len(df)
    q0 = np.asarray(calib.calib_config["q0"], dtype=float)
    q = np.tile(q0, (N, 1))
    for j_id, name in enumerate(calib.model.names[1:], start=1):
        name = str(name)
        if name in df.columns:
            idx = calib.model.joints[j_id].idx_q
            q[:, idx] = df[name].to_numpy()
    calib.q_measured = q
    calib.session_ids = df["session_id"].to_numpy().astype(int)
    calib._fk_config["NbSample"] = N
    # _compute_logmap_residuals (core) reads calib_config["NbSample"] and
    # PEE_measured's own length, not _fk_config's -- all three must stay
    # in sync for a held-out split (PEE_measured is always the zero
    # vector -- the flush-contact target -- just resized).
    calib.calib_config["NbSample"] = N
    calib.PEE_measured = np.zeros(3 * N)


def _print_metrics(label: str, before: dict, after: dict) -> None:
    print(f"\n{label}")
    for key, unit in (
        ("z_rmse_mm", "mm"),
        ("roll_rmse_deg", "deg"),
        ("pitch_rmse_deg", "deg"),
    ):
        factor = before[key] / after[key] if after[key] > 1e-12 else float("inf")
        print(
            f"  {key:16s} {before[key]:8.4f} {unit} -> {after[key]:8.4f} {unit}"
            f"   ({factor:5.1f}x reduction)"
        )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--regenerate",
        action="store_true",
        help="Resynthesize data instead of loading the committed demo CSVs.",
    )
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument(
        "--noise-deg",
        type=float,
        default=0.0,
        help="Joint-encoder noise std, in degrees (0 = noiseless).",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="If set, write a YAML + HTML calibration report here "
        "(default: results/, use --no-save-results to skip).",
    )
    parser.add_argument(
        "--no-save-results",
        action="store_true",
        help="Don't write any report files, just print to stdout.",
    )
    parser.add_argument(
        "--archive",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=(
            "Archive this run to results/runs/<asset>/calibration/"
            "<timestamp>/ (provenance, config snapshot, parameters, and "
            "the HTML report) and append a summary line to "
            "results/runs/index.jsonl. Never overwrites a prior run. "
            "Use --no-archive to skip. Ignored with --no-save-results."
        ),
    )
    args = parser.parse_args()
    save_results = not args.no_save_results
    archive = save_results and args.archive
    results_root = args.output_dir or str(HERE / "results")

    if args.regenerate or not (DATA_DIR / "table_contact_train.csv").exists():
        df_train, df_val, ground_truth, robot = build_dataset(
            seed=args.seed, encoder_noise_std=np.deg2rad(args.noise_deg)
        )
    else:
        from generate_synthetic_data import _load_robot

        robot = _load_robot()
        df_train = pd.read_csv(DATA_DIR / "table_contact_train.csv")
        df_val = pd.read_csv(DATA_DIR / "table_contact_validation.csv")
        with open(DATA_DIR / "ground_truth.json") as f:
            ground_truth = json.load(f)

    print(f"Training touches:   {len(df_train)}")
    print(f"Validation touches: {len(df_val)}")

    train_path = DATA_DIR / "_run_train.csv"
    df_train.to_csv(train_path, index=False)

    calib = TalosTableContactCalibration(robot, str(CONFIG_PATH))
    calib.calib_config["data_file"] = str(train_path)
    calib._data_path = str(train_path)

    nominal_poses = [
        NOMINAL_TABLE_POSE * cartesian_to_SE3([dx, dy, 0.0, 0.0, 0.0, 0.0])
        for dx, dy in ground_truth["session_offsets"]
    ]
    calib.set_nominal_table_poses(nominal_poses)
    calib.set_nominal_contact_offset(NOMINAL_CONTACT_OFFSET)
    calib.initialize()
    train_path.unlink(missing_ok=True)

    print(
        f"\nChain: {calib.calib_config['start_frame']} -> "
        f"{calib.calib_config['end_frame']}"
    )
    print(f"Identifiable joint-placement (Delta X) parameters: {calib.n_deltaX}")
    print(
        f"Sessions: {calib.n_sessions}  "
        f"(+3 plane params each, +3 shared contact-frame params)"
    )
    print(f"Total calibrated parameters: {len(calib.calib_config['param_name'])}")

    var0 = np.zeros(len(calib.calib_config["param_name"]))
    train_before = calib.gap_metrics(var0)

    # Standard FIGAROH calibration entry point (as
    # examples/tiago/calibration.py uses) -- runs solve_optimisation()'s
    # outlier-removal loop, then _evaluate_solution()/calc_stddev(),
    # printing the same terminal quality report TIAGo's own calibration
    # prints. See TalosTableContactCalibration.get_pose_from_measure /
    # cost_function for how this class feeds its plane/contact gap
    # residual through core's own SE3 log-map machinery instead of a
    # bespoke one.
    result = calib.solve(
        method="lm",
        max_iterations=3,
        outlier_threshold=3.0,
        enable_logging=False,
        html_report=False,  # exported explicitly below, with a chosen path
    )

    train_after = calib.gap_metrics(result.x)
    _print_metrics(
        "Training-set gap (postures the solver saw):", train_before, train_after
    )

    # Held-out validation: done manually here, not via BaseCalibration's
    # own _compute_validation_metrics/_load_validation_data -- those call
    # calc_updated_fkm(..., self.calib_config) directly with the *full*
    # param_name list, which includes this class's PLANE_TPL/CONTACT_TPL
    # entries that aren't raw joint-offset parameters and make that path
    # assert-fail (see TalosTableContactCalibration._compute_validation_metrics,
    # overridden to return None so solve() itself doesn't crash on this).
    _load_split(calib, df_val)
    val_before = calib.gap_metrics(var0)
    val_after = calib.gap_metrics(result.x)
    _print_metrics(
        "Held-out validation gap (postures it never saw):", val_before, val_after
    )

    if save_results:
        run_dir = compute_run_dir(calib, root=str(Path(results_root) / "runs"))
        html_path = str(run_dir / "synthetic_calibration_report.html")
        yaml_path = str(run_dir / "synthetic_master_calibration.yaml")
        calib.export_html_report(output_path=html_path)
        export_geometric_calibration_yaml(
            calib,
            yaml_path,
            header_comment="TALOS table-contact calibration (synthetic)",
        )
        if archive:
            archive_run(calib, run_dir)
        print(f"\nRun archived to:\n  {run_dir}")

    split = calib.split_params(result.x)
    print(
        "\nRecovered plane / contact-frame corrections "
        "(vs. injected ground truth -- see README for why these are "
        "expected to differ somewhat from the raw injected values):"
    )
    for s in range(calib.n_sessions):
        true = ground_truth["plane_true"][s]
        est = {
            "z": split["plane"][f"plane_z_s{s}"],
            "phix": split["plane"][f"plane_phix_s{s}"],
            "thetay": split["plane"][f"plane_thetay_s{s}"],
        }
        print(
            f"  session {s} plane   true: z={true['z']*1e3:+.3f}mm "
            f"phix={np.rad2deg(true['phix']):+.4f}deg "
            f"thetay={np.rad2deg(true['thetay']):+.4f}deg"
        )
        print(
            f"                   estimated: z={est['z']*1e3:+.3f}mm "
            f"phix={np.rad2deg(est['phix']):+.4f}deg "
            f"thetay={np.rad2deg(est['thetay']):+.4f}deg"
        )

    ct_true = ground_truth["contact_true"]
    ct_est = split["contact"]
    print(
        f"  contact frame   true: z={ct_true['z']*1e3:+.3f}mm "
        f"phix={np.rad2deg(ct_true['phix']):+.4f}deg "
        f"thetay={np.rad2deg(ct_true['thetay']):+.4f}deg"
    )
    print(
        f"              estimated: z={ct_est['contact_z']*1e3:+.3f}mm "
        f"phix={np.rad2deg(ct_est['contact_phix']):+.4f}deg "
        f"thetay={np.rad2deg(ct_est['contact_thetay']):+.4f}deg"
    )


if __name__ == "__main__":
    main()
